#!/usr/bin/env bash

set -e

: ${SCRIPT_DIR:=scripts}

ask() {
    local Q="${1}"
    while true; do
        read -p "${Q}" ANS
        case $ANS in
            [aA]ll|[aA]* )
                all
                break
                ;;

            [cC]hoose|[cC]* )
                choose
                break
                ;;
            * )
                echo "Acceptable inputs: [A/a]ll or [C/c]hoose."
                ;;
          esac
   done
}

all() {
    shopt -s nullglob
    local SCRIPTS=($SCRIPT_DIR/*)
    shopt -u nullglob

    for SCRIPT in ${SCRIPTS[@]}; do
        echo "Running $SCRIPT"
        bash $SCRIPT
    done
}

choose() {
    echo "Here are available scripts to run:"
    declare -A SCRIPT_MAP
    shopt -s nullglob
    local SCRIPTS=($SCRIPT_DIR/*)
    shopt -u nullglob
    local C=0
    for SCRIPT in ${SCRIPTS[@]}; do
        SCRIPT_MAP[$C]=$SCRIPT
        ((C=C+1))
    done
    for K in ${!SCRIPT_MAP[@]}; do
        echo "[$K]: $(basename ${SCRIPT_MAP[$K]})"
    done
    read -p "Please enter the number of the script you want to run: " OPT
    if [[ "${SCRIPT_MAP[$OPT]+foobar}" ]]; then
        echo "Running: ${SCRIPT_MAP[$OPT]}"
        bash "${SCRIPT_MAP[$OPT]}"
    else
        echo "Wrong or non-existent choice. Bye."
        exit
    fi
}

echo "Hello, Welcome to the workspace setup script."
ask "You can run [a]ll the scripts in $SCRIPT_DIR or [c]hoose from a list > "
