#!/usr/bin/env bash

sudo apt-get update && sudo apt install -y \
    git vim ssh zsh curl \
    tmux terminator autojump \
    silversearcher-ag cowsay cowsay-off \
    fortunes fortune-mod fortunes-off \
    redshift i3 fonts-powerline i3status suckless-tools \
    i3lock xbacklight feh conky lxappearance \
    scrot compton unclutter flameshot \
    pulseaudio-module-zeroconf sane \
    build-essential libssl-dev \
    libffi-dev python-dev \
    python-pip python-setuptools \
    python-virtualenv rbenv ruby-build \
    fonts-font-awesome fonts-inconsolata font-hack
