#!/usr/bin/env bash

PIPS=(ansible awscli)

for PIP in ${PIPS[@]}; do
    echo "Installing $PIP via pip"
    pip install $PIP --upgrade --user
    echo "$PIP installation successful"
done

PIP3S=(sncli)

for PIP3 in ${PIP3S[@]}; do
    echo "Installing $PIP3 via pip"
    pip3 install $PIP3 --upgrade --user
    echo "$PIP3 installation successful"
done
