#!/usr/bin/env bash

source $(dirname $0)/.helpers
scriptpath
# SCRIPTPATH is a global var output from the scriptpath function
BINPATH=$(dirname $SCRIPTPATH)/bin

[[ -e $HOME/.bin ]] && rm $HOME/.bin
ln -snfv $BINPATH $HOME/.bin
