#!/usr/bin/env bash
# Symlink helpers/<file> to /usr/local/bin/<file>

# turn on nullglob to get array of files without wonky use of ls
shopt -s nullglob
HELPERS=(helpers/*)
shopt -u nullglob

HELPDIR=/usr/local/bin

# iterate through files array and symlink it to the $HOME directory
for H in ${HELPERS[@]}; do
    HELPER=$(basename $H)
    HELP=$HELPDIR/$HELPER
    # remove existing symlinks
    [[ -f $HELP ]] && rm -rfv $HELP
    # symlink files
    sudo ln -snfv $(pwd)/helpers/$HELPER $HELP
done
