#!/usr/bin/env bash

# Symlink configs/<file> to ~/.config/<type>/config

# turn on nullglob to get array of files without wonky use of ls
shopt -s nullglob
CONFIGS=(configs/*)
shopt -u nullglob

# iterate through files array and symlink it to the $HOME directory
for CONF in ${CONFIGS[@]}; do
    APP=$(basename ${CONF})
    APP_CONFIG=$HOME/.config/$APP/config
    APP_CONFIG_DIR=$HOME/.config/$APP
    # remove existing configfile/config file links
    [[ ! -d $APP_CONFIG_DIR ]] && mkdir -pv $APP_CONFIG_DIR
    [[ -e $APP_CONFIG ]] && rm -rfv $APP_CONFIG
    # link config files here
    ln -snfv $(pwd)/$CONF $APP_CONFIG
done
