#!/usr/bin/env bash

sudo apt-get update && sudo apt install -y \
    apt-transport-https autoconf autojump automake \
    build-essential \
    ca-certificates compton conky cowsay \
    cowsay-off cryptsetup curl \
    feh fonts-firacode fonts-font-awesome fonts-hack-ttf \
    fonts-hack-web fonts-inconsolata fortune-mod fortunes  \
    git gnupg \
    kitty \
    libbz2-dev libffi-dev liblzma-dev \
    libncurses5-dev libncurses-dev \
    libncursesw5-dev libreadline-dev libsqlite3-dev \
    libssl-dev libtool libxslt1-dev libyaml-dev \
    make mdadm \
    nmap \
    pinentry-curses \
    scrot silversearcher-ag software-properties-common ssh steghide  \
    tk-dev tmux \
    unclutter unixodbc-dev unzip \
    vim \
    wget whois wireguard \
    xclip xsel xz-utils \
    zlib1g-dev zsh
