#!/usr/bin/env bash

images=(
https://github.com/VSCodium/vscodium/releases/download/1.43.1/VSCodium-1.43.1-1584565098.glibc2.16-x86_64.AppImage
https://github.com/standardnotes/desktop/releases/download/v3.3.3/Standard-Notes-3.3.3.AppImage
)
