#!/usr/bin/env bash

sudo apt install -y \
  automake autoconf libreadline-dev \
  libncurses-dev libssl-dev libyaml-dev \
  libxslt-dev libffi-dev libtool unixodbc-dev \
  unzip curl

if [[ ! -d ~/.asdf ]]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  cd ~/.asdf
  git checkout "$(git describe --abbrev=0 --tags)"
  asdf update
fi


source ${HOME}/.asdf/asdf.sh
source ${HOME}/.asdf/completions/asdf.bash

plugins=(direnv golang kubectl \
  minikube nodejs nomad packer python ruby \
  shellcheck solidity \
  terraform terraform-docs \
  terraform-validator terragrunt tflint \
  vault yq)

for plugin in ${plugins[@]}; do
  asdf plugin add $plugin
  asdf install $plugin latest
done
