#!/usr/bin/env bash

source $(dirname $0)/.helpers

DIST=$(lsb_release -i | awk '{ print $3 }')

[[ "$DIST" != "Ubuntu" ]] && echo "Not Ubuntu... bail.." && exit

echos "Running clean-up of old packages" apt-get remove -y docker docker-engine docker.io
update
echos "Installing needed packages"  apt install -y \
      apt-transport-https \
      ca-certificates \
      curl \
      software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

echos "Verifying key fingerprint..." apt-key fingerprint 0EBFCD88
ask "Does this look alright? [yes/no]? "

echos "Adding Docker CE repos" add-apt-repository \
      "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) \
      stable"

update
echos "Installing latest Docker CD" apt install -y docker-ce

ME=$(whoami)
echos "Adding $ME to docker group" gpasswd -a $ME docker


echos "Enabling docker service startup" systemctl enable docker.service
echos "Restarting docker service"  systemctl restart docker.service

echo "Finished installing Docker CE"
