#!/usr/bin/env bash

sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install -y flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

APPS=(
com.slack.Slack
org.telegram.desktop
org.gottcode.FocusWriter
work.openpaper.Paperwork
com.visualstudio.code.oss
com.jetbrains.IntelliJ-IDEA-Community
org.signal.Signal
com.bitwarden.desktop
io.github.hakuneko.HakuNeko
com.valvesoftware.Steam
)


for APP in "${APPS[@]}"; do
    flatpak install -y flathub "$APP"
done
