#!/usr/bin/env bash

sudo apt-get install -y \
  fonts-firacode fonts-hack-ttf


URLS=(
https://github.com/belluzj/fantasque-sans/releases/download/v1.7.2/FantasqueSansMono-Normal.zip
)

# Download bare font packages into the local font directory
FONTS_DIR=${HOME}/.fonts

[[ ! -d ${FONTS_DIR} ]] && mkdir -v ${FONTS_DIR} && cd ${FONTS_DIR}

for URL in ${URLS[@]}; do
    FPKG="$(basename ${URL})"
    curl -fsSLO ${URL}
    echo "Finished downloading ${FPKG}"
    if [[ "${FKG##*.}" == "zip" ]]; then
        unzip -u ${FPKG}
    fi
done

# cleanup
rm -rfv *.zip image

# update the fonts
fc-cache -f -v
