#!/usr/bin/env bash

URLS=(
https://github.com/belluzj/fantasque-sans/releases/download/v1.7.2/FantasqueSansMono-Normal.zip
)

# Download bare font packages into the local font directory
FONTS_DIR=${HOME}/.fonts

[[ ! -d ${FONTS_DIR} ]] && mkdir -v "${FONTS_DIR}" && cd "${FONTS_DIR}" || return

for URL in "${URLS[@]}"; do
    FPKG=$(basename "${URL}")
    curl -fsSLO "${URL}"
    echo "Finished downloading ${FPKG}"
    if [[ "${FPKG##*.}" == "zip" ]]; then
        unzip -u "${FPKG}"
    fi
done

# cleanup
rm -rfv ./*.zip image

# update the fonts
fc-cache -f -v
