#!/usr/bin/env bash

# Manual instructions for trying to install Guitar Rig 5 on Ubuntu with Wine

cat << EOF

## Wine configuration
$ sudo mount Downloads/Guitar_Rig_5.iso wine.isos -t udf -o loop,ro,exec,unhide
$ wine wine.isos/Guitar\ Rig\ 5\ 5.2.2\ Setup\ PC.exe
1.  Add override to msvcr120.dll in winecfg libraries

## Post Wine config
1. Install jackd2 and qjackctl
2. Install wineasio from kxstudio repositories
3. Register wineasio dlls (regsvr32 wineasio && wine64 regsvr32 wineasio)
4. Connect your USB interface and start qjackctl
5. Run GuitarRig5 and choose wineasio as interface
6. Enjoy
EOF
