#!/usr/bin/env bash

VAULT_VERSION=0.11.1
ARCH=amd64
VAULT_GPGKEY=91A6E7F85D05C65630BEF18951852D87348FFC4C
FOUND=''

for server in \
    hkp://p80.pool.sks-keyservers.net:80 \
    hkp://keyserver.ubuntu.com:80 \
    hkp://pgp.mit.edu:80 \
; do \
    echo "Fetching GPG key $VAULT_GPGKEY from $server"; \
    gpg --keyserver "$server" --recv-keys "$VAULT_GPGKEY" && FOUND=yes && break; \
done; \
test -z "$FOUND" && echo >&2 "Error: Failed to fetch GPG key $VAULT_GPGKEY" && exit 1; \

mkdir -p /tmp/build && \
cd /tmp/build && \
wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_${ARCH}.zip && \
wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS && \
wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS.sig && \
gpg --batch --verify vault_${VAULT_VERSION}_SHA256SUMS.sig vault_${VAULT_VERSION}_SHA256SUMS && \
grep vault_${VAULT_VERSION}_linux_${ARCH}.zip vault_${VAULT_VERSION}_SHA256SUMS | sha256sum -c && \
sudo unzip -d /usr/local/bin vault_${VAULT_VERSION}_linux_${ARCH}.zip && \
cd /tmp && \
rm -rf /tmp/build
