#!/usr/bin/env bash

sudo apt-get update && sudo apt install -y \
  git vim ssh zsh curl tmux terminator autojump \
  silversearcher-ag cowsay cowsay-off fortunes fortune-mod fortunes-off \
  suckless-tools feh conky lxappearance scrot compton unclutter flameshot \
  pulseaudio-module-zeroconf sane \
  libffi-dev make build-essential libssl-dev zlib1g-dev libbz2-dev \
  libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
  xz-utils tk-dev libffi-dev liblzma-dev python-openssl git
